### ISSUE TITLE
Graphical console not configured for guest/GPU is not isolated for passthrough!

### ISSUE THREAD

**Issue by jon-bit** [lexi-src/sGPUpt#28]
When I run the script I get 
```
#############################################################
#                ♥ sGPUpt made by lexi-src ♥                #
# Report issues @ https://github.com/lexi-src/sGPUpt/issues #
#############################################################
[sGPUpt][CHOICE] Enter VM name: game
[sGPUpt][ERROR] GPU is not isolated for passthrough!

```
I have seen #16 and it has no fix for me. I tried its fix but If I say no to 
```
Couldn't find any passable USB, continue without USB? [Y/n]:
```
It quits and if say yes when I lunch my VM it just gives my a black screen where it says 
```
Graphical console not configured for guest
```
At this point this is the best script I have seen so far and it is 100% compatible with my hardware but I don't know how to make it work. Does anyone have a fix?

**Comment by lexi-src** [comment]
Please run this script then reply with the result.
```bash
#!/bin/bash
shopt -s nullglob
for g in $(find /sys/kernel/iommu_groups/* -maxdepth 0 -type d | sort -V); do
    echo "IOMMU Group ${g##*/}:"
    for d in $g/devices/*; do
        echo -e "\t$(lspci -nns ${d##*/})"
    done;
done;
```

**Comment by jon-bit** [comment]
IOMMU Group 0:
	00:00.0 Host bridge [0600]: Intel Corporation Comet Lake-S 6c Host Bridge/DRAM Controller [8086:9b33] (rev 05)
IOMMU Group 1:
	00:01.0 PCI bridge [0604]: Intel Corporation 6th-10th Gen Core Processor PCIe Controller (x16) [8086:1901] (rev 05)
	01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104 [GeForce RTX 3070 Ti] [10de:2482] (rev a1)
	01:00.1 Audio device [0403]: NVIDIA Corporation GA104 High Definition Audio Controller [10de:228b] (rev a1)
IOMMU Group 2:
	00:14.0 USB controller [0c03]: Intel Corporation Tiger Lake-H USB 3.2 Gen 2x1 xHCI Host Controller [8086:43ed] (rev 11)
	00:14.2 RAM memory [0500]: Intel Corporation Tiger Lake-H Shared SRAM [8086:43ef] (rev 11)
IOMMU Group 3:
	00:15.0 Serial bus controller [0c80]: Intel Corporation Tiger Lake-H Serial IO I2C Controller #0 [8086:43e8] (rev 11)
	00:15.1 Serial bus controller [0c80]: Intel Corporation Tiger Lake-H Serial IO I2C Controller #1 [8086:43e9] (rev 11)
IOMMU Group 4:
	00:16.0 Communication controller [0780]: Intel Corporation Tiger Lake-H Management Engine Interface [8086:43e0] (rev 11)
IOMMU Group 5:
	00:17.0 SATA controller [0106]: Intel Corporation Device [8086:43d2] (rev 11)
IOMMU Group 6:
	00:1b.0 PCI bridge [0604]: Intel Corporation Device [8086:43c0] (rev 11)
IOMMU Group 7:
	00:1b.4 PCI bridge [0604]: Intel Corporation Device [8086:43c4] (rev 11)
IOMMU Group 8:
	00:1c.0 PCI bridge [0604]: Intel Corporation Device [8086:43b8] (rev 11)
IOMMU Group 9:
	00:1c.5 PCI bridge [0604]: Intel Corporation Device [8086:43bd] (rev 11)
IOMMU Group 10:
	00:1c.6 PCI bridge [0604]: Intel Corporation Device [8086:43be] (rev 11)
IOMMU Group 11:
	00:1c.7 PCI bridge [0604]: Intel Corporation Device [8086:43bf] (rev 11)
IOMMU Group 12:
	00:1d.0 PCI bridge [0604]: Intel Corporation Tiger Lake-H PCI Express Root Port #9 [8086:43b0] (rev 11)
IOMMU Group 13:
	00:1f.0 ISA bridge [0601]: Intel Corporation Device [8086:4385] (rev 11)
	00:1f.3 Audio device [0403]: Intel Corporation Device [8086:f0c8] (rev 11)
	00:1f.4 SMBus [0c05]: Intel Corporation Tiger Lake-H SMBus Controller [8086:43a3] (rev 11)
	00:1f.5 Serial bus controller [0c80]: Intel Corporation Tiger Lake-H SPI Controller [8086:43a4] (rev 11)
IOMMU Group 14:
	03:00.0 Non-Volatile memory controller [0108]: Sandisk Corp WD Blue SN570 NVMe SSD [15b7:501a]
IOMMU Group 15:
	05:00.0 Ethernet controller [0200]: Intel Corporation Ethernet Controller I225-V [8086:15f3] (rev 03)
IOMMU Group 16:
	06:00.0 Ethernet controller [0200]: Intel Corporation Ethernet Controller I225-V [8086:15f3] (rev 03)
IOMMU Group 17:
	07:00.0 Network controller [0280]: Intel Corporation Wi-Fi 6 AX210/AX211/AX411 160MHz [8086:2725] (rev 1a)
IOMMU Group 18:
	08:00.0 Non-Volatile memory controller [0108]: Samsung Electronics Co Ltd NVMe SSD Controller SM981/PM981/PM983 [144d:a808]

**Comment by lexi-src** [comment]
Your GPU isn't isolated properly.
```
IOMMU Group 1:
00:01.0 PCI bridge [0604]: Intel Corporation 6th-10th Gen Core Processor PCIe Controller (x16) [8086:1901] (rev 05)
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104 [GeForce RTX 3070 Ti] [10de:2482] (rev a1)
01:00.1 Audio device [0403]: NVIDIA Corporation GA104 High Definition Audio Controller [10de:228b] (rev a1)
```
This is what an isolated GPU looks like.
```
IOMMU Group 1
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104 [GeForce RTX 3070 Ti] [10de:2482] (rev a1)
01:00.1 Audio device [0403]: NVIDIA Corporation GA104 High Definition Audio Controller [10de:228b] (rev a1)
```

The ACS patch may resolve this issue but it's not guaranteed.

**Comment by jon-bit** [comment]
I'm on fedora. How do I get the ACS patch?

**Comment by lexi-src** [comment]
I haven't tried it on Fedora but I assume you'll have to manually patch it then recompile the kernel.

**Comment by jon-bit** [comment]
any guides on how to do that?

**Comment by lexi-src** [comment]
unfortunately I don't have anything to provide.

**Comment by jon-bit** [comment]
OK now I'm on mint and the same thing is happening. I'm not sure whats going on but I'm not sure if I'm doing something wrong.

**Comment by lexi-src** [comment]
I'm not exactly sure what you want me to do with such vague information.

**Comment by jon-bit** [comment]
What do you need? I'll supply anything you want.

**Comment by lexi-src** [comment]
Well I'll assume that you're running into the same issue as before with your IOMMU groups not isolated properly.

Try adding `intel_iommu=on iommu=pt` to grub (save then reboot) then run this script again:
```bash
#!/bin/bash
shopt -s nullglob
for g in $(find /sys/kernel/iommu_groups/* -maxdepth 0 -type d | sort -V); do
    echo "IOMMU Group ${g##*/}:"
    for d in $g/devices/*; do
        echo -e "\t$(lspci -nns ${d##*/})"
    done;
done;
```

**Comment by jon-bit** [comment]
I had it set befor I got the same thing 
```
IOMMU Group 0:
	00:00.0 Host bridge [0600]: Intel Corporation Comet Lake-S 6c Host Bridge/DRAM Controller [8086:9b33] (rev 05)
IOMMU Group 1:
	00:01.0 PCI bridge [0604]: Intel Corporation 6th-10th Gen Core Processor PCIe Controller (x16) [8086:1901] (rev 05)
	01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104 [GeForce RTX 3070 Ti] [10de:2482] (rev a1)
	01:00.1 Audio device [0403]: NVIDIA Corporation GA104 High Definition Audio Controller [10de:228b] (rev a1)
IOMMU Group 2:
	00:14.0 USB controller [0c03]: Intel Corporation Tiger Lake-H USB 3.2 Gen 2x1 xHCI Host Controller [8086:43ed] (rev 11)
	00:14.2 RAM memory [0500]: Intel Corporation Tiger Lake-H Shared SRAM [8086:43ef] (rev 11)
IOMMU Group 3:
	00:15.0 Serial bus controller [0c80]: Intel Corporation Tiger Lake-H Serial IO I2C Controller #0 [8086:43e8] (rev 11)
	00:15.1 Serial bus controller [0c80]: Intel Corporation Tiger Lake-H Serial IO I2C Controller #1 [8086:43e9] (rev 11)
IOMMU Group 4:
	00:16.0 Communication controller [0780]: Intel Corporation Tiger Lake-H Management Engine Interface [8086:43e0] (rev 11)
IOMMU Group 5:
	00:17.0 SATA controller [0106]: Intel Corporation Device [8086:43d2] (rev 11)
IOMMU Group 6:
	00:1b.0 PCI bridge [0604]: Intel Corporation Device [8086:43c0] (rev 11)
IOMMU Group 7:
	00:1b.4 PCI bridge [0604]: Intel Corporation Device [8086:43c4] (rev 11)
IOMMU Group 8:
	00:1c.0 PCI bridge [0604]: Intel Corporation Device [8086:43b8] (rev 11)
IOMMU Group 9:
	00:1c.5 PCI bridge [0604]: Intel Corporation Device [8086:43bd] (rev 11)
IOMMU Group 10:
	00:1c.6 PCI bridge [0604]: Intel Corporation Device [8086:43be] (rev 11)
IOMMU Group 11:
	00:1c.7 PCI bridge [0604]: Intel Corporation Device [8086:43bf] (rev 11)
IOMMU Group 12:
	00:1d.0 PCI bridge [0604]: Intel Corporation Tiger Lake-H PCI Express Root Port #9 [8086:43b0] (rev 11)
IOMMU Group 13:
	00:1f.0 ISA bridge [0601]: Intel Corporation Device [8086:4385] (rev 11)
	00:1f.3 Audio device [0403]: Intel Corporation Device [8086:f0c8] (rev 11)
	00:1f.4 SMBus [0c05]: Intel Corporation Tiger Lake-H SMBus Controller [8086:43a3] (rev 11)
	00:1f.5 Serial bus controller [0c80]: Intel Corporation Tiger Lake-H SPI Controller [8086:43a4] (rev 11)
IOMMU Group 14:
	03:00.0 Non-Volatile memory controller [0108]: Sandisk Corp WD Blue SN570 NVMe SSD [15b7:501a]
IOMMU Group 15:
	05:00.0 Ethernet controller [0200]: Intel Corporation Ethernet Controller I225-V [8086:15f3] (rev 03)
IOMMU Group 16:
	06:00.0 Ethernet controller [0200]: Intel Corporation Ethernet Controller I225-V [8086:15f3] (rev 03)
IOMMU Group 17:
	07:00.0 Network controller [0280]: Intel Corporation Wi-Fi 6 AX210/AX211/AX411 160MHz [8086:2725] (rev 1a)
IOMMU Group 18:
	08:00.0 Non-Volatile memory controller [0108]: Samsung Electronics Co Ltd NVMe SSD Controller SM981/PM981/PM983 [144d:a808]
```

**Comment by jon-bit** [comment]
Wait did you mean fedora or mint? That's fedora.

**Comment by lexi-src** [comment]
please post the output of both commands:

`cat /proc/cmdline`
```bash
#!/bin/bash
shopt -s nullglob
for g in $(find /sys/kernel/iommu_groups/* -maxdepth 0 -type d | sort -V); do
    echo "IOMMU Group ${g##*/}:"
    for d in $g/devices/*; do
        echo -e "\t$(lspci -nns ${d##*/})"
    done;
done;
```

**Comment by jon-bit** [comment]
cat /proc/cmdline
```
BOOT_IMAGE=(hd3,gpt2)/vmlinuz-6.2.10-201.fsync.fc37.x86_64 root=UUID=da142f7d-42a1-46ee-b6d2-b63a4859ad07 ro rootflags=subvol=root rhgb quite intel_iommu=on iommu=pt rd.driver.blacklist=nouveau modprobe.blacklist=nouveau
```
bash script
```
IOMMU Group 0:
	00:00.0 Host bridge [0600]: Intel Corporation Comet Lake-S 6c Host Bridge/DRAM Controller [8086:9b33] (rev 05)
IOMMU Group 1:
	00:01.0 PCI bridge [0604]: Intel Corporation 6th-10th Gen Core Processor PCIe Controller (x16) [8086:1901] (rev 05)
	01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104 [GeForce RTX 3070 Ti] [10de:2482] (rev a1)
	01:00.1 Audio device [0403]: NVIDIA Corporation GA104 High Definition Audio Controller [10de:228b] (rev a1)
IOMMU Group 2:
	00:14.0 USB controller [0c03]: Intel Corporation Tiger Lake-H USB 3.2 Gen 2x1 xHCI Host Controller [8086:43ed] (rev 11)
	00:14.2 RAM memory [0500]: Intel Corporation Tiger Lake-H Shared SRAM [8086:43ef] (rev 11)
IOMMU Group 3:
	00:15.0 Serial bus controller [0c80]: Intel Corporation Tiger Lake-H Serial IO I2C Controller #0 [8086:43e8] (rev 11)
	00:15.1 Serial bus controller [0c80]: Intel Corporation Tiger Lake-H Serial IO I2C Controller #1 [8086:43e9] (rev 11)
IOMMU Group 4:
	00:16.0 Communication controller [0780]: Intel Corporation Tiger Lake-H Management Engine Interface [8086:43e0] (rev 11)
IOMMU Group 5:
	00:17.0 SATA controller [0106]: Intel Corporation Device [8086:43d2] (rev 11)
IOMMU Group 6:
	00:1b.0 PCI bridge [0604]: Intel Corporation Device [8086:43c0] (rev 11)
IOMMU Group 7:
	00:1b.4 PCI bridge [0604]: Intel Corporation Device [8086:43c4] (rev 11)
IOMMU Group 8:
	00:1c.0 PCI bridge [0604]: Intel Corporation Device [8086:43b8] (rev 11)
IOMMU Group 9:
	00:1c.5 PCI bridge [0604]: Intel Corporation Device [8086:43bd] (rev 11)
IOMMU Group 10:
	00:1c.6 PCI bridge [0604]: Intel Corporation Device [8086:43be] (rev 11)
IOMMU Group 11:
	00:1c.7 PCI bridge [0604]: Intel Corporation Device [8086:43bf] (rev 11)
IOMMU Group 12:
	00:1d.0 PCI bridge [0604]: Intel Corporation Tiger Lake-H PCI Express Root Port #9 [8086:43b0] (rev 11)
IOMMU Group 13:
	00:1f.0 ISA bridge [0601]: Intel Corporation Device [8086:4385] (rev 11)
	00:1f.3 Audio device [0403]: Intel Corporation Device [8086:f0c8] (rev 11)
	00:1f.4 SMBus [0c05]: Intel Corporation Tiger Lake-H SMBus Controller [8086:43a3] (rev 11)
	00:1f.5 Serial bus controller [0c80]: Intel Corporation Tiger Lake-H SPI Controller [8086:43a4] (rev 11)
IOMMU Group 14:
	03:00.0 Non-Volatile memory controller [0108]: Sandisk Corp WD Blue SN570 NVMe SSD [15b7:501a]
IOMMU Group 15:
	05:00.0 Ethernet controller [0200]: Intel Corporation Ethernet Controller I225-V [8086:15f3] (rev 03)
IOMMU Group 16:
	06:00.0 Ethernet controller [0200]: Intel Corporation Ethernet Controller I225-V [8086:15f3] (rev 03)
IOMMU Group 17:
	07:00.0 Network controller [0280]: Intel Corporation Wi-Fi 6 AX210/AX211/AX411 160MHz [8086:2725] (rev 1a)
IOMMU Group 18:
	08:00.0 Non-Volatile memory controller [0108]: Samsung Electronics Co Ltd NVMe SSD Controller SM981/PM981/PM983 [144d:a808]
```

**Comment by lexi-src** [comment]
Okay so technically your Group 1 can be used for passthough but the script isn't allowing it because of the PCI bridge.

So here's your options:
1. I can provide a function with predefined information to get the script working.
2. I can provide information on how to setup the ACS patch.

The option 1 is safer.

**Comment by jon-bit** [comment]
yha let's do 1. I don't wanna do any harm to my PC.

**Comment by lexi-src** [comment]
replace line 167 with:
```c
gpu_components=3
```
add this on line 177 directly under `find_pcie_devices`:
```c
array_gpu[0] = 00:01.0
array_gpu[1] = 01:00.0
array_gpu[2] = 01:00.1
```

**Comment by jon-bit** [comment]
OK now what?

**Comment by lexi-src** [comment]
Try running the script.

**Comment by jon-bit** [comment]
```
#############################################################
#                ♥ sGPUpt made by lexi-src ♥                #
# Report issues @ https://github.com/lexi-src/sGPUpt/issues #
#############################################################
[sGPUpt][CHOICE] Enter VM name: game-on
./sGPUpt.sh: line 177: array_gpu[0]: command not found
./sGPUpt.sh: line 178: array_gpu[1]: command not found
./sGPUpt.sh: line 179: array_gpu[2]: command not found
[sGPUpt][ERROR] GPU is not isolated for passthrough!

```

**Comment by lexi-src** [comment]
I edited the previous post, please try the last part once more.

**Comment by jon-bit** [comment]
the output is
```
#############################################################
#                ♥ sGPUpt made by lexi-src ♥                #
# Report issues @ https://github.com/lexi-src/sGPUpt/issues #
#############################################################
[sGPUpt][CHOICE] Enter VM name: game-on
[sGPUpt][CHOICE] Couldn't find any passable USB, continue without USB? [Y/n]: Y
[sGPUpt][INFO] Running package check.
Last metadata expiration check: 1:07:57 ago on Thu 13 Apr 2023 06:22:48 PM EDT.
Package qemu-kvm-2:7.2.0-4.fc38.x86_64 is already installed.
Package virt-manager-4.1.0-1.fc37.noarch is already installed.
Package virt-viewer-11.0-5.fc37.x86_64 is already installed.
Package virt-install-4.1.0-1.fc37.noarch is already installed.
Package libvirt-daemon-config-network-9.0.0-1.fc38.x86_64 is already installed.
Package libvirt-daemon-kvm-9.0.0-1.fc38.x86_64 is already installed.
Package swtpm-0.8.0-2.fc38.x86_64 is already installed.
Package gcc-c++-12.2.1-2.fc37.x86_64 is already installed.
Package ninja-build-1.11.1-1.fc38.x86_64 is already installed.
Package nasm-2.15.05-3.fc37.x86_64 is already installed.
Package acpica-tools-20220331-4.fc37.x86_64 is already installed.
Package libuuid-devel-2.38.1-1.fc37.x86_64 is already installed.
Package glib2-devel-2.74.1-2.fc38.x86_64 is already installed.
Package pixman-devel-0.40.0-6.fc37.x86_64 is already installed.
Package spice-protocol-0.14.4-3.fc38.noarch is already installed.
Package spice-server-devel-0.15.0-5.fc37.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
[sGPUpt][CHOICE] Do you want to create a drive named game-on? [y/N]: y
[sGPUpt][CHOICE] Size of disk (GB)[default 128]: 250
["VM Configuration"]
{
  "System Type":"Intel"
  "Name":"game-on"
  "vCPU":"18"
  "Memory":"32768M"
  "Disk":"250G"
  "QEMU Version":"7.2.0"
  "Additional Devices": [ 00:01.0 01:00.0 01:00.1  ]
}
[sGPUpt][INFO] Adding additional features/optimizations to game-on...
[sGPUpt][SUCCESS] Successfully created passthrough hooks!
[sGPUpt][SUCCESS] Finished creating game-on!
[sGPUpt][SUCCESS] Open virt-manager then add your chosen OS to CDROM1 then start the VM
```
but when I start the VM I get 
```
Error starting domain: internal error: Non-endpoint PCI devices cannot be assigned to guests

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 108, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1402, in startup
    self._backend.create()
  File "/usr/lib64/python3.11/site-packages/libvirt.py", line 1373, in create
    raise libvirtError('virDomainCreate() failed')
libvirt.libvirtError: internal error: Non-endpoint PCI devices cannot be assigned to guests
```

**Comment by lexi-src** [comment]
Looks like you need to ACS patch. Are you okay with that?

**Comment by jon-bit** [comment]
I guess

**Comment by jon-bit** [comment]
Actually one sec
I be back in a bit

**Comment by lexi-src** [comment]
```bash
wget -qO - https://dl.xanmod.org/archive.key | sudo gpg --dearmor -o /usr/share/keyrings/xanmod-archive-keyring.gpg

echo 'deb [signed-by=/usr/share/keyrings/xanmod-archive-keyring.gpg] http://deb.xanmod.org releases main' | sudo tee /etc/apt/sources.list.d/xanmod-release.list

sudo apt update && sudo apt install linux-xanmod-x64v3
```

add this to grub: `pcie_acs_override=downstream,multifunction`

reboot

**Comment by jon-bit** [comment]
I can't do apt. I'm on fedora.

**Comment by lexi-src** [comment]
> OK now I'm on mint and the same thing is happening. I'm not sure whats going on but I'm not sure if I'm doing something wrong.

**Comment by jon-bit** [comment]
And then I said this
> Wait did you mean fedora or mint? That's fedora.

**Comment by lexi-src** [comment]
I cannot assist you any further.

**Comment by jon-bit** [comment]
OK in that case let me boot up into my mint drive

**Comment by jon-bit** [comment]
sorry but now Mint will not boot

**Comment by lexi-src** [comment]
Please reply when your machine is ready.

**Comment by jon-bit** [comment]
I did what you said but not I can't get into to mint.

**Comment by lexi-src** [comment]
My instructions would not destroy an install.

Please reply when your machine is ready.

**Comment by jon-bit** [comment]
OK I just reinstalled 4 times and followed your instructions. It did not work and I came to a deadlock everytime.

**Comment by lexi-src** [comment]
Hello jon-bit, the latest version of the script should work with your system without having to use the ACS patch.

I've learned a bit more about IOMMU groups and made some changes to exclude certain devices.

If this solves your problem then please close this issue.
