### ISSUE TITLE
Error starting domain: Cannot recv data: Connection reset by peer

### ISSUE THREAD

**Issue by tmedina567** [lexi-src/sGPUpt#38]
Error starting domain: Cannot recv data: Connection reset by peer

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 108, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1402, in startup
    self._backend.create()
  File "/usr/lib/python3.10/site-packages/libvirt.py", line 1373, in create
    raise libvirtError('virDomainCreate() failed')
libvirt.libvirtError: Cannot recv data: Connection reset by peer

**Comment by lexi-src** [comment]
Which distro did this occur on? When did this happen?

**Comment by tmedina567** [comment]
Hi, this occurred on Endeavouros and like 15 mins ago.

**Comment by lexi-src** [comment]
Did it happen after the script finished executing?

**Comment by tmedina567** [comment]
The scipt ran successfully. This happened when i tried the run the VM after adding my iso to SATA CDROM 1.

**Comment by lexi-src** [comment]
Try running:
>sudo systemctl restart libvirtd

and if that doesn't work then try:

>sudo reboot

**Comment by tmedina567** [comment]
Hey no luck, still getting the same error.

**Comment by lexi-src** [comment]
Any errors in the output of this command?
>sudo systemctl status libvirtd

**Comment by tmedina567** [comment]
● libvirtd.service - Virtualization daemon
     Loaded: loaded (/usr/lib/systemd/system/libvirtd.service; enabled; preset: disabled)
     Active: active (running) since Fri 2023-04-28 21:17:54 EDT; 1min 1s ago
TriggeredBy: ● libvirtd.socket
             ● libvirtd-admin.socket
             ● libvirtd-ro.socket
       Docs: man:libvirtd(8)
             https://libvirt.org
   Main PID: 602 (libvirtd)
      Tasks: 22 (limit: 32768)
     Memory: 36.2M
        CPU: 367ms
     CGroup: /system.slice/libvirtd.service
             ├─602 /usr/bin/libvirtd --timeout 120
             ├─758 /usr/bin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/lib/libvirt/libvirt_leaseshelper
             └─759 /usr/bin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/lib/libvirt/libvirt_leaseshelper

Apr 28 21:17:56 terrance-alienwareaurorar7 dnsmasq-dhcp[758]: DHCP, sockets bound exclusively to interface virbr0
Apr 28 21:17:56 terrance-alienwareaurorar7 dnsmasq[758]: no servers found in /etc/resolv.conf, will retry
Apr 28 21:17:56 terrance-alienwareaurorar7 dnsmasq[758]: read /etc/hosts - 7 names
Apr 28 21:17:56 terrance-alienwareaurorar7 dnsmasq[758]: read /var/lib/libvirt/dnsmasq/default.addnhosts - 0 names
Apr 28 21:17:56 terrance-alienwareaurorar7 dnsmasq-dhcp[758]: read /var/lib/libvirt/dnsmasq/default.hostsfile
Apr 28 21:18:01 terrance-alienwareaurorar7 dnsmasq[758]: reading /etc/resolv.conf
Apr 28 21:18:01 terrance-alienwareaurorar7 dnsmasq[758]: using nameserver 192.168.1.1#53
Apr 28 21:18:03 terrance-alienwareaurorar7 dnsmasq[758]: reading /etc/resolv.conf
Apr 28 21:18:03 terrance-alienwareaurorar7 dnsmasq[758]: using nameserver 192.168.1.1#53
Apr 28 21:18:03 terrance-alienwareaurorar7 dnsmasq[758]: using nameserver 2600:4041:422c:cb00::1#53

**Comment by lexi-src** [comment]
>firewall-cmd --list-all --zone=libvirt

**Comment by tmedina567** [comment]
libvirt (active)
  target: ACCEPT
  icmp-block-inversion: no
  interfaces: virbr0
  sources: 
  services: dhcp dhcpv6 dns ssh tftp
  ports: 
  protocols: icmp ipv6-icmp
  forward: no
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
        rule priority="32767" reject

**Comment by lexi-src** [comment]
I've never seen this error before on any system, maybe you can try look for a solution by searching:
>Error starting domain: Cannot recv data: Connection reset by peer

**Comment by kevinboss** [comment]
I am having the same error on Pop!_OS (22.04)

**Comment by AnOpenSauceDev** [comment]
Exact same problem, usually happens to me after spamming run because the VM refused to start.

**Comment by greengeckowizard** [comment]
I'm also having the same problem too on Linux Mint 21.2  AMD CPU and Nvidia GPU with UEFI and CSM is off too
